### ISSUE TITLE
１回のpingでも複数フックされる

### ISSUE THREAD

**Issue by masibw** [Tomo-9925/go_study#5]
```ping hoge -c 1 ```
を実行しても

``` debug: debug mode
debug: create and bind to queue specified by QueueNum
debug: signal handling
debug: packet handling
srcPort:57987
inode:5484081
{Pid: 20152, PPid: 15959, Executable: ping, Path: /usr/bin/ping} <nil>
srcPort:57987
inode:5484081
{Pid: 20152, PPid: 15959, Executable: ping, Path: /usr/bin/ping} <nil>
srcPort:53
inode:0
{Pid: 25929, PPid: 25926, Executable: nginx, Path: /usr/sbin/nginx} <nil>
srcPort:53
inode:0
{Pid: 25929, PPid: 25926, Executable: nginx, Path: /usr/sbin/nginx} <nil>
srcPort:0
inode:0
{Pid: 25929, PPid: 25926, Executable: nginx, Path: /usr/sbin/nginx} <nil>
srcPort:0
inode:0
{Pid: 25929, PPid: 25926, Executable: nginx, Path: /usr/sbin/nginx} <nil>
srcPort:51373
inode:5484085
{Pid: 20152, PPid: 15959, Executable: ping, Path: /usr/bin/ping} <nil>
srcPort:53
inode:0
{Pid: 25929, PPid: 25926, Executable: nginx, Path: /usr/sbin/nginx} <nil>
キューの設定を元に戻しました． 

```
という風に複数フックされます。また、pingが取れている部分もありますがinodeが0で失敗（nginxが取得されている)ものもあります。

**Comment by Tomo-9925** [comment]
これは，どこからどこに対してpingをしましたか…？詳細を教えていただけると嬉しいです．

**Comment by masibw** [comment]
詳細まで書いていなくてすいません

docker コンテナ内(研究環境の src_port_2)で
``` ping mesimasi.com -c 1 ```
を実行した結果です

**Comment by Tomo-9925** [comment]
Pingは，ICMP Echo Requestが2つ飛んでる（かもしれない）って感じですよね…？

検証に使ったアプリのソースコード上げていただけますか？
（もし、すでにあればブランチやコミットハッシュ値を教えていただけますか？）

**Comment by masibw** [comment]
masterブランチ : 1be75a84cc3b1c3613ff8eb584b5335cb422253a

で実行しました

研究環境で
/home/僕のk番/go/src/github.com/Tomo-9925/go_study/cmd/packet_monitor
で run.shを実行すれば該当の環境で実行できます

**Comment by masibw** [comment]
ごめんなさい見落としてました
> Pingは，ICMP Echo Requestが2つ飛んでる（かもしれない）って感じですよね…？

pingと取得されてるのは3つあるので3回 ICMP Echo Requestが飛んでるかもしれないですね（多分？）

今 DOCKER-ISOLATION-STAGE-1 でフックしてるので IN とOUT両方取得してる可能性はあります（この仮定で取得回数が奇数なのはおかしいですが）
取得するチェーンがもっといいものがあるのか そもそもそう言う仕様なのか色々調べる必要がありそうです・・

**Comment by masibw** [comment]
- 取得するchainはDOCKER-USERで良さそう
- 上記については ICMPプロトコルを取得できるシステムにはなっていないので仕様通りなのを勘違いしていた

ということでcloseして良さそうでしょうか？
