### ISSUE TITLE
loopの中でdefer するとリソースリークするらしい

### ISSUE THREAD

**Issue by masibw** [Tomo-9925/go_study#7]
# loopの中でdefer するとリソースリークするらしい
https://github.com/Tomo-9925/go_study/blob/1abf3c4db1385c798b03fbb51c0bb445ff36aafb/pkg/utility/packet.go#L97

deferするために保持していくのが原因ぽいです
関数を作成してあげると良いらしいです（そのうち直したい）

(参考リンク)
https://log.shinofara.xyz/2016/07/golang%E3%81%AEfor%E6%96%87%E3%81%AE%E4%B8%AD%E3%81%A7file%E3%82%92%E9%96%8B%E3%81%84%E3%81%A6%E9%96%89%E3%81%98%E3%81%A6%E3%81%9F%E3%82%89%E3%83%8F%E3%83%9E%E3%81%A3%E3%81%9F%E3%81%AE%E3%81%A7%E6%9B%B8%E3%81%8D%E6%AE%8B%E3%81%99/

**Comment by Tomo-9925** [comment]
コンテナの情報を取得する処理をファイルの読み込みではなく，SDKで殴れないだろうか🤔 
少し調べてみる…

**Comment by masibw** [comment]
以前SDK見てたときはパケット情報を得られないかに注目しすぎてたので、コンテナ情報を取得できる可能性は全然ありますね・・

（ただ、このissueの箇所は/proc/{containerPid}/net/tcp(udp) を開いてる処理なのでここはどうしようもない感はあります）

**Comment by Tomo-9925** [comment]
deferを使わないという方法で行くしかないかな？
for文のときは気をつけよう🤯
